### ISSUE TITLE
Views could use a templating system

### ISSUE THREAD

**Issue by jrha** [stfc/mimic#20]
All the views output a very similar HTML structure, which could be summed up as follows:

``` html
<div class='metagroup'>
  <h2 class='metagroup'>METAGROUP_NAME</h2>
  <div class="group" id="GROUP_NAME">
    <h5 class="group">GROUP_NAME</h5>
    <span id="n_NODE" onclick="node('FQDN')" class="node TAGS" title="DETAILS"></span>
    ...more nodes...
  </div>
  ...more groups...
</div>
...more metagroups...
```

This is a perfect fit for some kind of templating system, even if it is just a common piece of PHP which renders a standardised data structure (nested associative arrays?).

**Comment by GooBall** [comment]
Would something like [twig](http://twig.sensiolabs.org) or [django](https://www.djangoproject.com) be sensible?

**Comment by jrha** [comment]
Absolutely, but perhaps overkill?
Also, php is itself a templating engine.
