### ISSUE TITLE
Make use of dependency managers

### ISSUE THREAD

**Issue by jrha** [stfc/mimic#21]
We make use of several external projects to provide us with various bits of functionality:
- cookiecuttr
- jQuery
- jQuery UI
- jQuery Cookie plugin

Rather than shipping these ourselves, we could instead make use of dependency managers such as [Composer](https://getcomposer.org/), [npm](https://www.npmjs.com/) and [bower](http://bower.io/).

**Comment by GooBall** [comment]
At this time, I don't think this is something we need. That may change though.

**Comment by jrha** [comment]
Why not?

**Comment by GooBall** [comment]
We already have a small number of dependences - some of which could be cut out with a little work. At this moment in time, I think it would only be adding unnecessary weight to the project.

Further down the line it could make sense. But not as the project stands right now.

**Comment by jrha** [comment]
Cool, thanks.
