### ISSUE TITLE
Virtual Worker Nodes

### ISSUE THREAD

**Issue by apdibbo** [stfc/mimic#23]
Would it be possible to hide the vms in the Logical - Workers view which dont have a particular aquilon personality?

**Comment by GooBall** [comment]
I don't see why not.

**Comment by jrha** [comment]
Why wouldn't they have a personality? That would mean they aren't in aquilon at all.

**Comment by GooBall** [comment]
My understanding was that; he would like it if we didn't just have a sea of gray boxes for the vms on the workers view. Instead, we can display only the nodes that have something 'out of the ordinary'.

I could be wrong.

**Comment by jrha** [comment]
Ah, ok :smile:

**Comment by GRyall** [comment]
I would guess the desire is to only show VMs with a worker node personality on the worker node page. Might be wrong, but that would seem to make sense.

**Comment by jrha** [comment]
I have a suspicion that the personality remains the same and @alahiff is just running a special image.

**Comment by GRyall** [comment]
Now you say it, that does seem likely

**Comment by jrha** [comment]
You could accomplish the same effect by basing it on the batch state table though.

**Comment by apdibbo** [comment]
Hey, the ultimate effect is to see the ones which have been instantiated as worker nodes but to also catch ones which have been instantiated as worker nodes and the batch system hasn't started for whatever reason .

Talking it through with Andrew yesterday I've started developing a trigger for open Nebula to change the personality at instantiation so we can manage them through aquilon. I'm intending to write the trigger such that we can also surface it in the webfrontend

**Comment by jrha** [comment]
Cool, just be careful not to re-implement a monitoring system!
