### ISSUE TITLE
false matches on helpdesk section

### ISSUE THREAD

**Issue by GRyall** [stfc/mimic#40]
The help desk section on the host display shows tickets relating to the host. It searches for the host name in the subject line of the ticket. This is matching some false positives where the host name is contained within another - e.g. it matches vm14 for tickets with vm141 in (or would match tickets about hn1 for dev-hn1). Perhaps we could look for the short host name followed by end of string or any character not allowed in a hostname?

**Comment by GRyall** [comment]
This will be unhelpful: http://requesttracker.wikia.com/wiki/TicketSQL
Perhaps this is a little more complicated than I first thought.

**Comment by jrha** [comment]
Unfortunately this is a limitation of RT, it would require duplicate post processing to solve.
