### ISSUE TITLE
Feature Request - A way of finding the number of nodes in a cluster

### ISSUE THREAD

**Issue by RobAppleyard** [stfc/mimic#41]
Figuring out how many nodes in a larger cluster (eg. atlasStripInput in the Logical - Storage tab) is not trivial - in this case I figure it out by counting the number of both rows (7) and columns (9), do the multiplication (7*9 = 63) and then count missing columns (3) and subtracting this from the rows*columns (63-3 = 60).

It would be convenient not to have to do this arithmetic and give the system a way of telling the user this information in a simple manner, either by displaying it after the cluster title, as a hover pop-up, or some other similar means.

Failing that, a backup fix would be to lock the number of columns to 10 to make the arithmetic easier.

![Picture showing the ATLAS group](https://cloud.githubusercontent.com/assets/6586103/8476697/a026d082-20bb-11e5-8c12-8532643dd825.png)

**Comment by GRyall** [comment]
"a backup fix would be to lock the number of columns to 10 " or we could practice our times tables.

**Comment by RobAppleyard** [comment]
I still have to count the columns every time, because the number of them has changed in the past. I can do the arithmetic in my head, but I shouldn't have to and nobody else should either.

**Comment by GooBall** [comment]
Unfortunately, 'fixing' the number of columns is not an option as people use different sized monitors.

Adding a hover over (containing the number of nodes) to the title of a cluster will be simple.

**Comment by GooBall** [comment]
This has now been implemented. If you hover over a Cluster or Panel name a title tool tip will show the node count.
