### ISSUE TITLE
Add 'generation' or 'categoryName' to host's mouse-over pop-up in 'Logical - Storage' tab.

### ISSUE THREAD

**Issue by bmcann** [stfc/mimic#49]
Hi Callum,

Please consider adding the value of 'generation' or 'categoryName' to host's mouse-over pop-up window when viewing from the 'Logical - Storage' tab. It can be of great value to find out what hardware type a host is running on.

Thanks,
Bruno

**Comment by jrha** [comment]
Is clicking on a host too much effort?

**Comment by bmcann** [comment]
When I need info on one host: no, but when I want to see the generations of hardware that comprise a given cluster, I think this feature would be useful. For example, working out which generations of disk server are in a given instance of CASTOR.

**Comment by GooBall** [comment]
Hey Bruno, is this still a feature you would like? If so, might it be better to display this information via a new view - rather than cluttering the tooltips?
