### ISSUE TITLE
Cloud view contains hard-coded hostnames

### ISSUE THREAD

**Issue by jrha** [stfc/mimic#9]
The first few `file_get_contents()` calls use `$config['AQUILON']['URL']` but the calls further down still use a hard coded URL, this would cause interesting side effects for anyone else using the code!

**Comment by GooBall** [comment]
Just seen that when I was going through formatting it.

**Comment by jrha** [comment]
Can you close this from a commit (or pull-request) [as described here](https://help.github.com/articles/closing-issues-via-commit-messages/).
