### ISSUE TITLE
Selecting Non Existent Machines

### ISSUE THREAD

**Issue by apdibbo** [stfc/mimic#95]
When in the details Window you can click the next machine button to view machines which do not exist.
i.e. if you are view through lcg1860, lcg1861, lcg1862 then you can see lcg1863... which do not exist

**Comment by jrha** [comment]
Which is not surprising, because all it does is add or subtract 1 to any number found in the hostname.

**Comment by GooBall** [comment]
Considering the work and re-architecturing that would be required to check if the host exists before you can click the button, I can't say it would be worth it in the grand scheme of things.
